import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
import os
from datetime import datetime
from config import EMAIL_SENDER, EMAIL_PASSWORD, HR_EMAILS

class EmailReporter:
    def __init__(self):
        self.sender = EMAIL_SENDER
        self.password = EMAIL_PASSWORD
        self.recipients = HR_EMAILS
    
    def create_email_content(self, metrics: dict, predictions: list) -> str:
        """Create HTML email content"""
        html_content = f"""
        <html>
        <head>
            <style>
                body {{ font-family: Arial, sans-serif; margin: 20px; }}
                .header {{ background-color: #f4f4f4; padding: 20px; border-radius: 5px; }}
                .metrics {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0; }}
                .metric-card {{ background: white; padding: 15px; border-radius: 5px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }}
                .prediction-table {{ width: 100%; border-collapse: collapse; margin: 20px 0; }}
                .prediction-table th, .prediction-table td {{ padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }}
                .buy {{ color: green; font-weight: bold; }}
                .sell {{ color: red; font-weight: bold; }}
                .hold {{ color: orange; font-weight: bold; }}
            </style>
        </head>
        <body>
            <div class="header">
                <h1>📊 Weekly Financial Report</h1>
                <p>Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
            </div>
            
            <h2>📈 Executive Summary</h2>
            <p>This report contains automated analysis of financial data for the week ending {datetime.now().strftime('%Y-%m-%d')}.</p>
            
            <h2>📊 Key Metrics</h2>
            <div class="metrics">
        """
        
        # Add metrics
        for key, value in metrics.items():
            html_content += f"""
                <div class="metric-card">
                    <h3>{key.replace('_', ' ').title()}</h3>
                    <p style="font-size: 24px; font-weight: bold;">{value}</p>
                </div>
            """
        
        html_content += """
            </div>
            
            <h2>🔮 Predictions & Signals</h2>
            <table class="prediction-table">
                <tr>
                    <th>Ticker</th>
                    <th>Current Price</th>
                    <th>Predicted Price</th>
                    <th>Expected Return</th>
                    <th>Signal</th>
                    <th>Confidence</th>
                </tr>
        """
        
        # Add predictions
        for pred in predictions:
            signal_class = pred['signal'].lower().replace(' ', '-')
            html_content += f"""
                <tr>
                    <td>{pred['ticker']}</td>
                    <td>${pred['current_price']:.2f}</td>
                    <td>${pred['predicted_price']:.2f}</td>
                    <td>{pred['expected_return_pct']:.2f}%</td>
                    <td class="{signal_class}">{pred['signal']}</td>
                    <td>{pred['confidence']}</td>
                </tr>
            """
        
        html_content += """
            </table>
            
            <h2>📋 Attachments</h2>
            <p>This email includes the following attachments:</p>
            <ul>
                <li>Complete dataset (CSV)</li>
                <li>Analysis spreadsheet (Excel)</li>
                <li>Interactive dashboard (HTML)</li>
            </ul>
            
            <hr>
            <p><em>This is an automated report generated by the Financial Analytics System.</em></p>
            <p><em>For any questions, please contact the data analytics team.</em></p>
        </body>
        </html>
        """
        
        return html_content
    
    def send_email(self, subject: str, html_content: str, attachments: list):
        """Send email with attachments"""
        try:
            # Create message
            msg = MIMEMultipart()
            msg['From'] = self.sender
            msg['To'] = ', '.join(self.recipients)
            msg['Subject'] = subject
            
            # Add HTML content
            msg.attach(MIMEText(html_content, 'html'))
            
            # Add attachments
            for attachment in attachments:
                if os.path.exists(attachment):
                    with open(attachment, 'rb') as f:
                        part = MIMEBase('application', 'octet-stream')
                        part.set_payload(f.read())
                        encoders.encode_base64(part)
                        
                        filename = os.path.basename(attachment)
                        part.add_header(
                            'Content-Disposition',
                            f'attachment; filename="{filename}"'
                        )
                        msg.attach(part)
            
            # Send email
            with smtplib.SMTP('smtp.gmail.com', 587) as server:
                server.starttls()
                server.login(self.sender, self.password)
                server.send_message(msg)
            
            print(f"Email sent successfully to {len(self.recipients)} recipients")
            return True
            
        except Exception as e:
            print(f"Error sending email: {e}")
            return False
    
    def generate_weekly_report(self):
        """Generate and send weekly report"""
        from database_handler import DatabaseHandler
        from ml_predictor import FinancialPredictor
        
        db = DatabaseHandler()
        predictor = FinancialPredictor()
        
        # Get latest data
        latest_prices = db.get_latest_prices()
        
        # Calculate metrics
        total_tickers = len(latest_prices['Ticker'].unique())
        avg_return = latest_prices['Daily_Return'].mean() * 100
        total_volume = latest_prices['Volume'].sum()
        
        metrics = {
            'total_tickers_analyzed': total_tickers,
            'average_daily_return': f"{avg_return:.2f}%",
            'total_volume_traded': f"{total_volume:,.0f}",
            'report_date': datetime.now().strftime('%Y-%m-%d'),
            'data_points_analyzed': len(latest_prices)
        }
        
        # Generate predictions for all tickers
        predictions = []
        tickers = latest_prices['Ticker'].unique()
        
        for ticker in tickers[:5]:  # Limit to 5 for demo
            signal = predictor.generate_trading_signals(ticker)
            if signal:
                predictions.append(signal)
        
        # Create email content
        subject = f"Weekly Financial Report - {datetime.now().strftime('%Y-%m-%d')}"
        html_content = self.create_email_content(metrics, predictions)
        
        # Prepare attachments
        attachments = [
            'data/clean/consolidated_report.csv',
            'data/clean/analysis_report.xlsx',
            'dashboard_output.html'
        ]
        
        # Send email
        return self.send_email(subject, html_content, attachments)